import Head from "next/head"
import { NextPage } from "next"
import PhaserGame from "../components/PhaserGame"
// require("../components/PhaserGame")
import HelloWorldScene from "../scenes/HelloWorldScene"
import { useEffect } from "react"
// import Phaser from "phaser"
// import dynamic from 'next/dynamic'

const game: NextPage = () => {
    //@ts-ignore
    // const PhaserGame = window.PhaserGame
    // console.log(PhaserGame)

    const handleClick = () => {
        const scene = PhaserGame.scene.keys.helloworld as HelloWorldScene
        scene.createEmitter()
      }

      


    //   useEffect(async () => (window.Phaser = await import(`phaser`)), []);

    return (
        <>
        <Head>
            <title>RainbowKit App</title>
            <meta
                name="description"
                content="Generated by @rainbow-me/create-rainbowkit"
            />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div id="phaser-container"></div>
        <div>
            <button onClick={handleClick} className="text-zinc-200 text-2xl font-bold">Click Here</button>
        </div>
        

        </>
    )
}

export default game