import type { NextPage } from 'next';
import Head from 'next/head';
import Nav from '../components/Nav';
import PlayerSheetConainer from '../components/Player/PlayerSheetContainer';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>EPIC GAME NAME</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='h-[100vh] bg-[#2D2424]'>
        <Nav />
        <div className='flex justify-center'>
      <h1 className=' font-bold mt-10 text-2xl mb-5'>Mint a player</h1>
        </div>
      <PlayerSheetConainer />
      </div>
    </div>
  );
};

export default Home;
