import { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { useContractWrite, usePrepareContractWrite, useWaitForTransaction } from 'wagmi'
import Description from '../components/LootBoxes/Description'
import LootBox from '../components/LootBoxes/LootBox'
import Nav from '../components/Nav'
import { gearAbi } from '../lib/abi'
import GearMintModal from '../components/GearMintModal'

const Mintgear: NextPage = () => {

    const [isAnimating, setIsAnimating] = useState(false)
    const [isOpen, setIsOpen] = useState(false)
    const [isSuccesful, setIsSuccesfull] = useState(false)
    const [mintHash, setMintHash] = useState("");

    const handleGearMint = () => {
        setIsAnimating(true)
        mint?.();
        setIsOpen(true);
    }

    const gearContractAddress = "0xd6aedd59e179f53d2a270f7438f1e2edacde12cd"

    const { config } = usePrepareContractWrite({
      // @ts-ignore
      address: gearContractAddress,
      abi: gearAbi,
      functionName: "mint",
      args: [],
      onError(error) {
        console.log("Error", error);
      },
    });

    const {
      write: mint,
      isSuccess: isMintStarted,
      data: mintData,
    } = useContractWrite(config);

    const { isSuccess: txSuccess } = useWaitForTransaction({
      hash: mintData?.hash,
    });

    useEffect(() => {
      if (txSuccess) {
        setIsSuccesfull(true);
        setMintHash(mintData!.hash.toString());
      }
      console.log(mintData);
    }, [txSuccess]);

    return (
        <>
         <Head>
        <title>Block Crawler</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" type="image/png" href="/favicon-32x32.png" />
      </Head>
      <div>
        <GearMintModal isOpen={isOpen} setIsOpen={setIsOpen} isSuccesful={isSuccesful} setIsSuccesfull={setIsSuccesfull} />
            <Nav />
            <div className='w-full flex flex-col justify-center items-center'>
            <div className='bg-[#D5CEA3] flex justify-center items-center w-2/5 bg-opacity-40 mt-20 p-20 gap-20 rounded-xl'>
                <LootBox isAnimating={isAnimating} setIsAnimating={setIsAnimating} />
                <Description />
                
            </div>
            <button onClick={handleGearMint} className='bg-blue-500 hover:bg-blue-600 active:scale-95 hover:scale-105 text-zinc-200 p-2 mt-5 w-1/5 rounded-lg font-bold text-xl'>Mint</button>
            </div>
        </div>
        </>
    )
}

export default Mintgear