import type { NextPage } from "next";
import Head from "next/head";
import Nav from "../components/Nav";
import PlayersList from "../components/PlayersList";
import { createClient } from "urql";
import { useEffect, useState } from "react";

const players: NextPage = () => {
  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-[100vh] bg-[#2D2424]">
        <Nav />
        <div className="p-20">
          <PlayersList />
        </div>
      </div>
    </div>
  );
};

export default players;
