import type { NextPage } from 'next';
import Head from 'next/head';
import Nav from '../components/Nav';
import PlayerOwnedConatiner from '../components/PlayerOwnedContainer';
import PlayersList from '../components/PlayersList';
// import PlayerSheetConainer from '../components/PlayerSheetContainer';

const players: NextPage = () => {
  return (
    <div>
    <Head>
      <title>RainbowKit App</title>
      <meta
        name="description"
        content="Generated by @rainbow-me/create-rainbowkit"
      />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='h-[100vh] bg-zinc-900'>
      <Nav />
      <div className='p-20'>
      <PlayersList />
      </div>
    {/* <PlayerSheetConainer /> */}
    {/* <PlayerOwnedConatiner /> */}
    </div>
  </div>
  );
};

export default players;
